Repository katalon-studio/testops-junit5, pull requests merged in 2021-04, with the labels that each got.

#6 [TO-1351] Create Manual Trigger
  .github/workflows/manual-publish.yml
Labels: Extra Small

#4 Fix incompatibility due to new API
  pom.xml
  src/main/java/com/katalon/testops/junit5/helper/ReportHelper.java
  src/test/java/com/katalon/testops/junit5/Calculator.java
  src/test/java/com/katalon/testops/junit5/CalculatorTest.java
Labels: Small

#7 [TO-1351] Create version in Github using manual trigger
  .github/workflows/manual-publish-release-package.yml
  .github/workflows/publish_release_package.yml
Labels: Extra Small

#9 Update junit5 version from 1.0.0-SNAPSHOT to 1.0.0
  pom.xml
Labels: Extra Small

#8 [TO-1364] NPE when processing skip status, invalid error message
  src/main/java/com/katalon/testops/junit5/helper/ReportHelper.java
  src/main/java/com/katalon/testops/junit5/helper/TestRunManager.java
Labels: Extra Small

#10 Add profiles when public
  pom.xml
Labels: Medium
